### STAGE 1: Build ###
FROM node:16 AS build

WORKDIR  /app

COPY package.json /app

COPY package-lock.json  /app

RUN npm install

COPY . .

# EXPOSE 4200

# CMD  ["npm", "start"]


RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 4200


CMD ["nginx", "-g", "daemon off;"]



